### ISSUE TITLE
Addon not working on Blender 3.0.0

### ISSUE THREAD

**Issue by HaiseSaeye** [andyp123/blender_vertex_color_master#35]
Once you check it on doesnt appear, when you uncheck it this message appears.

![imagen](https://user-images.githubusercontent.com/99570315/153736203-ac5b277c-bea6-49a3-b594-ca3fca073aec.png)

**Comment by 13Stewartc** [comment]
I'm using 3.0 with this add-on and it works flawlessly :)

**Comment by HaiseSaeye** [comment]
good, it doesnt work for me

**Comment by cyso1988** [comment]
Same here.

Tested Blender 3.0.0 and Blender 3.0.1, both portable, and always deleted the Blender folder from /appdata/ to simulate a fresh install.
Many addons had similar problems with the change to 3.0.
Hope this great addon has not been abandoned, it is part of my workflow.

Thanks for the addon anyway.

![error](https://user-images.githubusercontent.com/44917874/155184640-8016b4c4-96f5-4b5a-8b93-2491a375a612.png)

**Comment by HaiseSaeye** [comment]
![imagen](https://user-images.githubusercontent.com/99570315/155892770-d2a9fadf-c4ff-42bf-8899-8b9cf6b22d51.png)
still persistent despite deleting the folder on appdata
any other idea?

**Comment by ssoher** [comment]
same here, blender 3.1.1 Steam version

**Comment by andyp123** [comment]
Firstly, I have not totally abandoned the addon, but certainly I have not worked on it for a long time - I think since 2.8 was released. Sorry for the lack of updates. There have been many changes to Blender, including some to the Python API that Vertex Color Master relies upon. Since it's now actually broken in 3.3 alpha builds, I am planning to start work on fixing as many bugs as I can and possibly adding a couple of new features. The new release is likely to require Blender 3.2 or above because the colour format has changed, and I don't want to maintain multiple versions.

In 3.2, if you use a vertex colour channel that is not of the format "face corner > byte color" there will be errors. I will have to modify the addon to properly support the different colour types. There are some other bugs that seem to be getting more troublesome for some users on more recent versions of Blender, although I personally didn't have any problems until 3.2.

**Comment by andyp123** [comment]
Doing good thanks! :) I've been using it for work, and it's actually been working fine in 3.3 alpha without me changing it. However, there are a lot of problems that can occur, so I'll try to fix as many of the issues that have cropped up since the last update, and pop in a couple features. Not going to promise any timeframe ;)

**Comment by 13Stewartc** [comment]
Glad you're doing good :) if you want an idea for a feature it'd be neat to be able to apply vertex paint to more than one object at a time. Rn it defaults to the last selected object when entering vertex mode. Meaning I can't vertex paint across different objects at once.

**Comment by andyp123** [comment]
As far as I'm aware, Blender doesn't support multi-object in sculpt or paint modes, and adding it is something outside of my comfort zone and probably the scope of this add-on. However, I could make some operators available in multi-object mode that don't involve painting. For example:
- Set colour
- Adjust HSV
- Gradient Fill
- Random island colours
I'm also considering a way to set the vertex colour based on surface normal and a vector, so you could smoothly fill a channel based on surfaces facing up, for example. This could also work in multi-object mode.

Do you have any operations you'd want to see supported in multi-object mode?

**Comment by 13Stewartc** [comment]
None come to mind but I'll keep thinking about it and get back to you if I come up with anything :D

**Comment by HaiseSaeye** [comment]
it works normally now, i had to reinstall the addon and be on vertex color tab to show up
