### ISSUE TITLE
When installing on Blender 4.2 an error occurs

### ISSUE THREAD

**Issue by RokudaimeObito** [andyp123/blender_vertex_color_master#51]
Add-on not loaded: "bl_ext.user_default.vertex_color_master", cause: module loaded with no associated file, __path__=_NamespacePath(['C:\\Users\\*MyUsername*\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\extensions\\user_default\\vertex_color_master']), aborting!

**Comment by Andrej730** [comment]
@RokudaimeObito 

To resolve this issue:
1) Open Preferences - Get Extensions - Uninstall "Vertex Color Master" as it was installed incorrectly.
2) Open vertex_color_master_0.9.0-alpha.zip and copy "blender_manifest.toml" to folder "vertex_color_master" inside zip file and then remove "blender_manifest.toml" from the zip root directory.
3) Try to install again.

@andyp123 blender_manifest.toml should be inside "vertex_color_master" folder, not in the zip root. Note that reinstalling fixed zip without uninstalling previously incorrectly installed version wouldn't work since Blender will detect that version in manifest in the same and will just ignore new .zip.

**Comment by andyp123** [comment]
Thanks for the help @Andrej730 . I must admit that after checking it was working in 4.2.0 directly from the source directory, I didn't try clean installing from the .zip I made as it was late at night for me and I was in a rush to get to bed. I've fixed the .toml packaging issue, tested from clean install and verified it works on 3.6, 4.0, 4.1 and 4.2.

Again, thanks for the help and thanks @RokudaimeObito for reporting the error.

**Comment by KruonDev** [comment]
> @RokudaimeObito
> 
> Bu sorunu çözmek için:
> 
> 1. Tercihler'i açın - Uzantıları edinin - "Vertex Color Master" yanlış yüklendiği için kaldırın.
> 2. vertex_color_master_0.9.0-alpha.zip dosyasını açın ve "blender_manifest.toml" dosyasını zip dosyasının içindeki "vertex_color_master" klasörüne kopyalayın ve ardından "blender_manifest.toml" dosyasını zip kök dizininden silin.
> 3. Tekrar yüklemeyi deneyin.
> 
> @andyp123blender_manifest.toml, zip kökünde değil, "vertex_color_master" klasörünün içinde olmalıdır. Blender, manifest dosyasındaki sürümün aynı olduğunu algılayacağı ve yeni .zip'i görmezden geleceği için, önceden yanlış yüklenen sürümü kaldırmadan sabit zip'i yeniden yüklemenin işe yaramayacağını unutmayın.

**Comment by KruonDev** [comment]
vertex color master ananın a ına girsin

**Comment by FreddeA87** [comment]
When I try to blend the vertex colors I get this error. Blender 4.2.7

I merged meshes with different color attribute names, and I want to take the colors from one color attribute and add it to another. 

Example.
Color attribute 1 is named A1 which is red.
Color attribute 2 is named A2 which is green.

I want to add the color from A2 to A1. Then I get the error below.

Python: Traceback (most recent call last):
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\vertex_color_master\vcm_ops.py", line 884, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\vertex_color_master\vcm_ops.py", line 895, in execute
    blend_channels(mesh, vi['src_vcol'], vi['dst_vcol'], vi['src_channel_idx'],
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\vertex_color_master\vcm_helpers.py", line 161, in blend_channels
    for i, src_av in enumerate(src_attr.data):
                               ^^^^^^^^
NameError: name 'src_attr' is not defined. Did you mean: 'setattr'?

**Comment by Andrej730** [comment]
@FreddeA87 It's better to start a separate issue for this, as your bug report is unrelated to the original problem discussed here.

Also, it seems your using not the latest version, since line 161 in your traceback is different from the current main, see - https://github.com/andyp123/blender_vertex_color_master/blob/master/vertex_color_master/vcm_helpers.py

So, please, try the latest version of the addon.

**Comment by FreddeA87** [comment]
Oops. sorry about that. I thought I clicked new issue, I am also new to github. 

I can make a new one so it can be tracked there instead
